install.packages("glmnet")
library(glmnet)
install.packages("ISLR")
library(ISLR)
attach(Credit)
summary(Credit)
which(is.na(Credit))
credit_matrix <- model.matrix(Income ~ Limit + Rating + Cards + Age + Education + Gender + Student + Married + Ethnicity + Balance)
credit_matrix$Intercept <- NULL
View(credit_matrix)
